version: 2.1

workflows:
    sylius2.x-tests:
        jobs:
            -   build:
                    name: php-<<matrix.php_version>>-sylius-<< matrix.sylius_version >>-symfony-<< matrix.symfony_version >>
                    matrix:
                        parameters:
                            # Symfony 6.4 support dropped due to doctrine/annotations compatibility issues
                            sylius_version: [ "2.1", "2.2" ]
                            php_version: [ "8.2", "8.3" ]
                            symfony_version: [ "7.4" ]

jobs:
    build:
        parameters:
            sylius_version:
                type: string
            symfony_version:
                type: string
            php_version:
                type: string
        machine:
            image: ubuntu-2204:current

        steps:
            - checkout
            -   run:
                    name: Build and start Docker containers
                    command: |
                        docker compose build --build-arg PHP_VERSION=<< parameters.php_version >>
                        docker compose up -d
            -   run: mkdir -p etc/build

            # Sylius & Symfony in current matrix versions
            -   run: ./bin-docker/composer require "sylius/sylius:<< parameters.sylius_version >>.*" --no-interaction --no-update --no-scripts
            -   run: grep -o -E '"(symfony/[^"]+)"' composer.json | grep -v -E '(symfony/flex|symfony/webpack-encore-bundle|symfony/maker-bundle|symfony/panther)' | xargs printf '%s:<< parameters.symfony_version >>.* '| xargs ./bin-docker/composer require --no-interaction --no-update

            -   run:
                    name: Wait for database
                    command: timeout 60s bash -c -- 'while ! docker compose exec -T mysql mysqladmin ping -h localhost --silent; do sleep 1; done'

            # COMPOSER PREFER DIST #
            -   run: ./bin-docker/composer update --no-interaction --prefer-dist --no-plugins
            -   run: ./bin-docker/docker-bash -c "rm -fr tests/Application/var/cache/*/*"
            -   run: ./bin-docker/yarn --cwd tests/Application install
            -   run: GULP_ENV=prod ./bin-docker/yarn --cwd tests/Application build
            -   run: (cd tests/Application && ../../bin-docker/php bin/console cache:clear --env=test)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console cache:warmup --env=test)
            -   run: ./bin-docker/docker-bash -c "APP_ENV=dev bin/phpstan.sh"
            -   run: ./bin-docker/docker-bash -c "APP_ENV=dev bin/ecs.sh --clear-cache"
            -   run: ./bin-docker/docker-bash -c "APP_ENV=dev bin/symfony-lint.sh"
            -   run: ./bin-docker/docker-bash -c "APP_ENV=dev bin/phpunit"
            -   run: (cd tests/Application && ../../bin-docker/php bin/console doctrine:database:drop --if-exists --env=test -vvv --force)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console doctrine:database:create --env=test -vvv)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console doctrine:migrations:migrate --no-interaction --env=test -vvv)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console doctrine:schema:update --complete --force --env=test -vvv)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console cache:clear --env=test -vvv)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console cache:warmup --env=test -vvv)
            -   run: ./bin-docker/docker-bash -c "APP_ENV=test php vendor/bin/behat"
            -   run: if [ -f tests/Application/var/log/test.log ]; then tail -n 50 tests/Application/var/log/test.log; fi

            # COMPOSER PREFER LOWEST (oldest possible) #
            # has to delete vendor for next test with different libraries version to avoid Composer error 'Failed to extract...' if vendor dir cache does not exist
            -   run: rm -fr composer.lock
            -   run: ./bin-docker/composer update --no-interaction --prefer-lowest --no-plugins
            -   run: ./bin-docker/docker-bash -c "rm -fr tests/Application/var/cache/*/*"
            -   run: ./bin-docker/yarn --cwd tests/Application install
            -   run: GULP_ENV=prod ./bin-docker/yarn --cwd tests/Application build
            -   run: (cd tests/Application && ../../bin-docker/php bin/console cache:clear --env=test)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console cache:warmup --env=test)
            -   run: ./bin-docker/docker-bash -c "APP_ENV=dev bin/phpstan.sh"
            -   run: ./bin-docker/docker-bash -c "APP_ENV=dev bin/ecs.sh --clear-cache"
            -   run: ./bin-docker/docker-bash -c "APP_ENV=dev bin/symfony-lint.sh"
            -   run: ./bin-docker/docker-bash -c "APP_ENV=dev bin/phpunit"
            -   run: (cd tests/Application && ../../bin-docker/php bin/console doctrine:database:drop --if-exists --env=test -vvv --force)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console doctrine:database:create --env=test -vvv)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console doctrine:migrations:migrate --no-interaction --env=test -vvv)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console doctrine:schema:update --complete --force --env=test -vvv)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console cache:clear --env=test -vvv)
            -   run: (cd tests/Application && ../../bin-docker/php bin/console cache:warmup --env=test -vvv)
            -   run: ./bin-docker/docker-bash -c "APP_ENV=test php vendor/bin/behat"
            -   run: if [ -f tests/Application/var/log/test.log ]; then tail -n 50 tests/Application/var/log/test.log; fi
